version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: haraka-postgres
    environment:
      POSTGRES_DB: haraka_db
      POSTGRES_USER: haraka_user
      POSTGRES_PASSWORD: haraka_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - haraka-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: haraka-backend
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: haraka_db
      DB_USER: haraka_user
      DB_PASSWORD: haraka_password
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - haraka-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx for reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: haraka-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - haraka-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  haraka-network:
    driver: bridge
