const vehiclesRoleColumns = {
  user: [
    "id",
    "code",
    "chassis_number",
    "vehicle_type",
    "vehicle_equipment",
    "plate_number_malaky",
    "plate_number_gesh",
    "plate_number_mokhabrat",
    "engine_number",
    "color",
    "gps_device_number",
    "line_number",
    "sector",
    "model_year",
    "fuel_type",
    "administration",
    "responsible_person",
    "supply_source",
    "insurance_status",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  admin: [
    "id",
    "code",
    "chassis_number",
    "vehicle_type",
    "vehicle_equipment",
    "plate_number_malaky",
    "plate_number_gesh",
    "plate_number_mokhabrat",
    "engine_number",
    "color",
    "gps_device_number",
    "line_number",
    "sector",
    "model_year",
    "fuel_type",
    "administration",
    "responsible_person",
    "supply_source",
    "insurance_status",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  viewer: [
    "id",
    "code",
    "chassis_number",
    "vehicle_type",
    "vehicle_equipment",
    "plate_number_malaky",
    "plate_number_gesh",
    "plate_number_mokhabrat",
    "engine_number",
    "color",
    "gps_device_number",
    "line_number",
    "sector",
    "model_year",
    "fuel_type",
    "administration",
    "responsible_person",
    "supply_source",
    "insurance_status",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  GPS: [
    "id",
    "code",
    "chassis_number",
    "vehicle_type",
    "vehicle_equipment",
    "plate_number_malaky",
    "plate_number_gesh",
    "plate_number_mokhabrat",
    // "engine_number",
    // "color",
    "gps_device_number",
    "line_number",
    "sector",
    // "model_year",
    // "fuel_type",
    "administration",
    "responsible_person",
    "supply_source",
    // "insurance_status",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  license: [
    "id",
    "code",
    "chassis_number",
    "vehicle_type",
    // "vehicle_equipment",
    "plate_number_malaky",
    // "plate_number_gesh",
    // "plate_number_mokhabrat",
    "engine_number",
    "color",
    // "gps_device_number",
    // "line_number",
    "sector",
    "model_year",
    "fuel_type",
    "administration",
    "responsible_person",
    "supply_source",
    // "insurance_status",
    "notes",
    "createdAt",
    "updatedAt",
  ],
};

module.exports = vehiclesRoleColumns;
