

[
  {
    code: 'TG2',
    chassis_number: '081830',
    vehicle_type: 'تويوتا لاند كروزر',
    vehicle_equipment: 'بيك اب 1 ك (دفع)',
    plate_number_mokhabrat: 'ر ل / 5498',
    plate_number_gesh: null,
    plate_number_malaky: 'بدون لوحات',
    engine_number: null,
    color: 'كاكى',
    gps_device_number: '22615854',
    line_number: '01503283624',
    sector: 'غرب VIP',
    model_year: 2015,
    fuel_type: 'بنزين',
    administration: 'غرب القاهرة',
    responsible_person: 'ض/ احمد شعراوي',
    supply_source: 'مشتريات سوق محلي',
    insurance_status: null,
    notes: null
  },
  {
    code: 'TC4',
    chassis_number: '_',
    vehicle_type: 'تويوتا ميني باص كوستر',
    vehicle_equipment: 'ركوب جماعى',
    plate_number_mokhabrat: null,
    plate_number_gesh: null,
    plate_number_malaky: null,
    engine_number: null,
    color: 'ابيض*ازرق',
    gps_device_number: null,
    line_number: null,
    sector: 'الضبعة',
    model_year: null,
    fuel_type: 'سولار',
    administration: 'مركز صيانة المركبات',
    responsible_person: null,
    supply_source: 'مشتريات سوق محلي',
    insurance_status: null,
    notes: null
  },
  {
    code: 'TC5',
    chassis_number: '_',
    vehicle_type: 'تويوتا ميني باص كوستر',
    vehicle_equipment: 'ركوب جماعى',
    plate_number_mokhabrat: null,
    plate_number_gesh: null,
    plate_number_malaky: null,
    engine_number: null,
    color: 'ابيض*ازرق',
    gps_device_number: null,
    line_number: null,
    sector: 'الضبعة',
    model_year: null,
    fuel_type: 'سولار',
    administration: 'مركز صيانة المركبات',
    responsible_person: null,
    supply_source: 'مشتريات سوق محلي',
    insurance_status: null,
    notes: null
  },
  {
    code: 'JK2',
    chassis_number: '1j4gx48s04c172535',
    vehicle_type: 'جيب جراند شروكى',
    vehicle_equipment: ' ركوب فردي',
    plate_number_mokhabrat: 'هـ هـ ن/743',
    plate_number_gesh: '471784/د',
    plate_number_malaky: null,
    engine_number: null,
    color: 'فضي',
    gps_device_number: '22655629',
    line_number: '01503306319',
    sector: 'الضبعة',
    model_year: 2004,
    fuel_type: 'بنزين',
    administration: 'مركز صيانة المركبات',
    responsible_person: 'لواء / علي خلوصي',
    supply_source: 'قوات جوية',
    insurance_status: null,
    notes: null
  },
  {
    code: null,
    chassis_number: null,
    vehicle_type: 'هاي لوكس',
    vehicle_equipment: 'بيك أب 2 ك ',
    plate_number_mokhabrat: null,
    plate_number_gesh: '466220',
    plate_number_malaky: null,
    engine_number: null,
    color: null,
    gps_device_number: null,
    line_number: null,
    sector: null,
    model_year: null,
    fuel_type: null,
    administration: null,
    responsible_person: null,
    supply_source: null,
    insurance_status: null,
    notes: null
  },
  {
    code: null,
    chassis_number: null,
    vehicle_type: 'ميكروباص هيونداي H1',
    vehicle_equipment: 'ركوب جماعي',
    plate_number_mokhabrat: null,
    plate_number_gesh: '445893',
    plate_number_malaky: null,
    engine_number: null,
    color: null,
    gps_device_number: null,
    line_number: null,
    sector: null,
    model_year: null,
    fuel_type: null,
    administration: null,
    responsible_person: null,
    supply_source: null,
    insurance_status: null,
    notes: null
  },
  {
    code: null,
    chassis_number: null,
    vehicle_type: 'دونج فينج',
    vehicle_equipment: 'ثلاجة',
    plate_number_mokhabrat: null,
    plate_number_gesh: '465922',
    plate_number_malaky: null,
    engine_number: null,
    color: null,
    gps_device_number: null,
    line_number: null,
    sector: null,
    model_year: null,
    fuel_type: null,
    administration: null,
    responsible_person: null,
    supply_source: null,
    insurance_status: null,
    notes: null
  },
  {
    code: null,
    chassis_number: null,
    vehicle_type: 'شيفورليه',
    vehicle_equipment: 'ثلاجة',
    plate_number_mokhabrat: null,
    plate_number_gesh: '467767',
    plate_number_malaky: null,
    engine_number: null,
    color: null,
    gps_device_number: null,
    line_number: null,
    sector: null,
    model_year: null,
    fuel_type: null,
    administration: null,
    responsible_person: null,
    supply_source: null,
    insurance_status: null,
    notes: null
  },
  {
    code: null,
    chassis_number: null,
    vehicle_type: 'ميتسوبيشي كانتر',
    vehicle_equipment: '120 حصان',
    plate_number_mokhabrat: null,
    plate_number_gesh: '467796',
    plate_number_malaky: null,
    engine_number: null,
    color: null,
    gps_device_number: null,
    line_number: null,
    sector: null,
    model_year: null,
    fuel_type: null,
    administration: null,
    responsible_person: null,
    supply_source: null,
    insurance_status: null,
    notes: null
  },
  {
    code: null,
    chassis_number: null,
    vehicle_type: 'نيسان',
    vehicle_equipment: 'بيك أب 2 ك',
    plate_number_mokhabrat: null,
    plate_number_gesh: '467795',
    plate_number_malaky: null,
    engine_number: null,
    color: null,
    gps_device_number: null,
    line_number: null,
    sector: null,
    model_year: null,
    fuel_type: null,
    administration: null,
    responsible_person: null,
    supply_source: null,
    insurance_status: null,
    notes: null
  }
]