name: Build and Deploy HARAKA

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: omarzakaria10/haraka
  FRONTEND_REPO: OmarZakaria10/HARAKA-ReactJS

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Backend Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install Backend Dependencies
      run: npm ci
      
    - name: Checkout Frontend Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ env.FRONTEND_REPO }}
        path: frontend-temp
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js for Frontend
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend-temp/package-lock.json
        
    - name: Install Frontend Dependencies
      working-directory: frontend-temp
      run: npm ci
      
    - name: Build Frontend
      working-directory: frontend-temp
      run: |
        CI=false npm run build
        
    - name: Copy Frontend Build to Backend
      run: |
        rm -rf build
        cp -r frontend-temp/build .
        ls -la build/
        
    - name: Run Tests
      run: |
        echo "Running tests..."
        # npm test
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,prefix={{branch}}-
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # For example: kubectl rollout restart deployment/haraka-backend
